name: HimlHisto
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.3.1
  - pip=20.1.1
  - python-blosc==1.7.0
  - python=3.7.3
  - pytorch=1.10.0
  - torchvision=0.11.1
  - pip:
      - PyJWT==1.7.1
      - azureml-sdk==1.36.0
      - azureml-tensorboard>=1.36.0
      - conda-merge>=0.1.5
      - cucim==21.10.1
      - dataclasses-json==0.5.2
      - hi-ml-azure>=0.1.8
      - hi-ml>=0.1.12
      - jinja2>=3.0.2
      - joblib==0.16.0
      - jupyter-client==6.1.5
      - jupyter==1.0.0
      - lightning-bolts==0.4.0
      - matplotlib>=3.4.3
      - mlflow==1.17.0
      - monai==0.6.0
      - more-itertools==8.10.0
      - mypy-extensions==0.4.3
      - numba==0.51.2
      - numpy==1.19.1
      - opencv-python-headless==4.5.1.48
      - pandas==1.3.4
      - param>=1.12
      - pillow==9.0.0
      - psutil==5.7.2
      - pydicom==2.0.0
      - pyflakes==2.2.0
      - pysocks>=1.5.8
      - pytest==7.0.1
      - pytorch-lightning>=1.5.5
      - rich==5.1.1
      - rpdb==0.1.6
      - ruamel.yaml>=0.16.12
      - runstats==1.8.0
      - scikit-image==0.17.2
      - scipy==1.5.2
      - seaborn==0.10.1
      - simpleitk==1.2.4
      - six==1.15.0
      - stopit==1.1.2
      - tabulate==0.8.7
      - tensorboard>=2.6.0
      - torch>=1.10.0
      - torchmetrics==0.6.0
      - torchvision>=0.11.1
      - types-python-dateutil==2.8.9
      - umap-learn==0.5.2
      - yacs==0.1.8